### PR TITLE
fix(lint): Ensure proper nesting of open/close tag brackets.

### LINKED ISSUE #2: Enhance _errorIfUnmatchedBrackets to check for proper nesting
IIUC, the `_errorIfUnmatchedBrackets` function currently just checks that there's the same number of `>` as there are `<` in the string.  We could enhance this to check for proper nesting, so that things like `> <` are rejected.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
`> <` is now considered bad HTML.

fixes #2 

@rfk - r?

### CODE REVIEW

File: test/check-translation-test.js [hunk 1]
```diff
@@ -157,7 +157,7 @@ exports.check_translations = {
 
   'malformed html - no opening or closing tag name': function (test) {
     checkTranslation(
-      '<>no opening tag name</>',
+      '<>no opening or closing tag name</>',
```
Comment (rfk) [inline test/check-translation-test.js]: Does this actually test the `</>` component of the string?  ISTM that it should always fail on the leading `<>` and we should have a separate test for just the `</>`.

**Comment by rfk** [comment]
r+; I had a comment but that could be a follow-up bug

File: test/check-translation-test.js (hunk 1 above)
Comment (shane-tomlinson) [inline test/check-translation-test.js]: > ISTM that it should always fail on the leading <>

That's the previous test.

> we should have a separate test for just the </>.

That's the next test.
